### ISSUE TITLE
Linking Refprop and TRNSYS

### ISSUE THREAD

**Issue by SBordi** [usnistgov/REFPROP-wrappers#245] opened 2020-01-23 17:22 UTC
Hi. I am working on creating a new TRNSYS 17 type linked with Refprop  (version 9.0).

### Description

My purpose is to create a new TRNSYS type using Fortran (Visual Studio Community 15) linked to Refprop, in order to use some fluid properties of CO2. To do so I have used a subroutine which creates a new type DLL. This DLL can read the .fld files thanks to the _fortran_ subroutines that I have added to the project through add/existing item. When using fluids such as R134a or R41 everything works fine and I obtain acceptable results in TRNSYS. However, when I switch to fluids like Ammonia or CO2, when running the Type in TRNSYS, I get this error:

Intel(r) Visual Fortran run-time error - forrtl: severe (59): list-directed I/O syntax error, unit 12, file c:\Program Files\Refprop\fluids\CO2.fld.

I guess the problem is in the linking between Fortran and TRNSYS (maybe when I call SETUP), because I tried to compile a simple project before proceeding with the subroutine and it worked fine also with CO2.
I really don't understand why it works with some fluids and not with the others.
Any suggestion will be very appreciated.

Many thanks.
Sara

**Comment by ianhbell** [comment] 2020-01-24 17:48
Hmm.. Could be that REFPROP 9 finds the fluid files from REFPROP 8, but I haven't run into that before.  I'd recommend first upgrading to REFPROP 10, for a lot of reasons, including better management of path issues. Where are your REFPROP 9 and REFPROP 8 files installed? What location does the environment variable RPPREFIX point to?

Definitely test in another environment (Python recommended), that will help to nail down what is going on.  There are more aggressive debugging options available as well if we need to make use of them (to see which files have been opened by the operating system, for instance).

**Comment by EricLemmon** [comment] 2020-01-24 21:23
We are working on a self-contained DLL that has all of the fluid files and mixture files embedded in it, but it only works with version 10.  If you would like to try this, please let me know (eric.lemmon@nist.gov).  It is brand new and probably has some bugs, but I would like some beta testing to find out how it is working.

**Comment by SBordi** [comment] 2020-02-12 12:00
Hi. As you suggested I upgraded to REFPROP 10. Now TRNSYS can read the other fluids, but I have problems in calling the subroutines for getting the properties of the fluids. For example, here there is a part of my code, some parts are taken from this forum:
   ```
program prova_forum
    implicit none
    integer, parameter :: ncmax=20,ipropmax=200
    double precision dummy1(ncmax),dummy2(ncmax),dummy3(ncmax)
    double precision x,xcalc,z(ncmax),Output(ipropmax)
    double precision P,T,x1,x2,x3,h,hf,hg,Q,PSAT,hsat,xv, &
        Teva,xliq,dv,dl,xvap,f
    integer iUnit,iMass,ierr,iFlag,iOut,nc,i
    character*255 hOut,herr,Refrigerant,hfld(ncmax),hfmix,hrf
    dimension x(ncmax),xliq(ncmax),xvap(ncmax),f(ncmax)
    Refrigerant='CO2'
    iMass=1 
    call SETPATH('C:\REFPROP\FLUIDS')
    NC=1
    hfld(1)='CO2.fld'
    hfmix='hmx.bnc'
    hrf='def'
    call SETUP (NC,hfld,hfmix,hrf,ierr,herr)
    if (ierr.ne.0) write (*,*) herr
    
    call GETENUM(0,'MASS BASE SI',iUnit,ierr,herr)
    call REFPROP (Refrigerant,' ',' ',iUnit,iMass,0,0d0,0d0,z,Output, &
    hout,iOut,dummy1,dummy2,dummy3,q,ierr,herr)   
     
    P = 1000000
    h = 250000 
    call REFPROP1('PH','T',iUnit,iMass,P,h,z,T,hf,ierr,herr)
    i=2
    Teva=273.15
    x=1
    call SATT (Teva,x,i,psat,dl,dv,xliq,xvap,ierr,herr)
```
This code works in a FORTRAN program, but it doesn’t in the FORTRAN subroutine used for TRNSYS. Or better, I can “build” the subroutine, but if I plot the results I obtain T=-9999990 as output from REFPROP1, while I obtain the right results for pressure and densities from SATT (but xvap=0, while it should be 1). 
Any suggestion on how to solve this problem?
Thank you very much.

**Comment by ianhbell** [comment] 2020-02-12 13:38
Suspect the issues has to do with path?  Does the call to ``SETUP`` work in both cases?  The call to ``SETPATH`` should be just to "C:/REFPROP", not "C:/REFPROP/FLUIDS"

Also, what reference state are you using? That could be your problem in ``REFPROP1``.  It is almost never a good idea to hard-code p,h inputs directly, better to calculate h from a set of pressure and temperature.

What are the values of ierr and herr in your failure case?

**Comment by SBordi** [comment] 2020-02-13 10:24
I tried to set the path you suggested and also to use the full path naming it "hfld(1)", with no changes in the results. 
I am not sure about what you mean by "used reference sate", but I guess I'm using the default reference state as my `hrf` variable is `DEF`?
I changed REFPROP1 call using PT inputs, but unfortunately this doesn't solve the problem.
here there is my code:

```
call SETPATH('C:\REFPROP')
    NC=1
    hfld(1)='CO2.fld'
    hfmix='hmx.bnc'
    hrf='def'
    call SETUP (NC,hfld,hfmix,hrf,ierr,herr)
    if (ierr.ne.0) write (*,*) herr
    call REFPROP (hfld(1),' ',' ',iUnit,iMass,0,0d0,0d0,z,Output, &
    hout,iOut,dummy1,dummy2,dummy3,q,ierr1,herr1)  
    Teva=273.15
    x=1
    call SATT (Teva,x,i,psat,dl,dv,xliq,xvap,ierr2,herr2)
    call REFPROP1('PT<','H',iUnit,iMass,Psat,Teva,z,Hs,hf,ierr3,herr3) 
```

My ierr and herr values, for the project and for the subroutine, are:
**PROJECT**

- REFPROP1 - ierr= 610, herr= [UNITCONV error 610] Requested unit is not available or array indices are out of bounds.

**SUBROUTINE**

- SETUP - ierr=102, herr=[SETUP error 102] Error in file or premature end of file for component 1: Carbon dioxide

- REFPROP - ierr=102, herr=[SETUP error 102] Error in file or premature end of file for component 1: Carbon dioxide

- SATT - ierr=0

- REFPROP1 - ierr=104,herr=[REFPROP error 104] No fluid files have been loaded. Please call SETUP, SETFLUIDS, SETMIX, or SETMIXTURE to select the pure fluid or mixture of interest. 
 
Sorry for not giving you this information before.

**Comment by ianhbell** [comment] 2020-02-13 13:26
The problem is clear: the CO2 fluid file is found but is not loading.  What precise version of REFPROP do you use? I think you need to reinstall REFPROP, which should reload the fluid files.

**Comment by SBordi** [comment] 2020-02-13 14:15
The version is REFPROP 10.0 (database 23). I tried to reinstall it, but the problem is still there. Is it possible that some links are missing? I mean, adding the .for files as source files seems to be sufficient to make the PROGRAM run. But what about the .inc files or the REFPROP.dll and REFPROP.lib files? Should they be linked somehow to the code? If yes, where? I tried to add their path to the properties of the project or to add them in "libraries" with no positive results.
Other question, should REFPROP be installed with some specific path?

**Comment by ianhbell** [comment] 2020-02-13 15:06
The .inc files are included implicitly by the build and should not need to be added automagically I believe.  The DLL and lib files are only needed if linking against the REFPROP library from another environment (e.g., C/C++).

Can you provide a bit more information about where you have installed REFPROP? Default location? You might also try absolute paths to the fluid files.  I don't use FORTRAN so I don't know whether this is a FORTRAN-specific problem.

**Comment by ianhbell** [comment] 2020-02-13 15:07
REFPROP works fine from C++, Python, etc. usually, so I suspect this is somehow a FORTRAN issue.  Have you tried the FORTRAN examples?

**Comment by SBordi** [comment] 2020-02-17 17:04
Hi, I managed to solve the problem. It was actually a TRNSYS issue. Thank you very much for your help.

**Comment by ianhbell** [comment] 2020-02-17 20:03
Good news, thanks for the update.  For posterity, can you please say a little bit about what the problem was?  And then please close the issue.

**Closed** 2020-04-03 20:10 UTC
Labels: enhancement, installation issues
