### ISSUE TITLE
Apparent memory leak when using the LabVIEW Wrapper in Windows 7

### ISSUE THREAD

**Issue by P-Erickson** [usnistgov/REFPROP-wrappers#70] opened 2018-10-09 16:40 UTC
### Description

I have developed an application that allows the use of the REFPROPdll in live data processing using LabVIEW.  The implementation allows for continuous calling of the dll at rates between 4 and 10Hz and has functioned with previous versions of REFPROP without issue.  However with the most recent release, the code will cause a crash of the LabVIEW environment (complete crash, not just a termination of the VI calling the dll) after a period of 8 and 12 hours consistently.  The error reporting generated during the crash is inconsistent, however generally points towards behavior that would be expected with a memory leak.  The implementation of the Call Library Function Node has been configured identically to the examples provided with the LabVIEW wrappers and based on my previous programming experience appears to be correct, with proper initialization of memory points and arrays.

### Steps to Reproduce

1. Call the REFPROPdll using the Call Library Function Node in LabVIEW
2. Repeat at a rate of 4Hz continuously for a period of 8+ hours.

**Expected behavior:** When I have performed similar calls to previous versions of the REFPROP functions (PDFLSH,TPFLSH,SATT, ect.) I have been able to execute the code in this manner without issue.  Performance of the dll appears to work as expected, calculation results match the values generated independently in Excel, and execution speed appears reasonable.  On initial execution, the code appears to be behaving as expected.

**Actual behavior:** After a period of executing for 8 or more hours, LabVIEW will crash and close completely.  Generating an error report using the build in NI Error Reporting server.  No errors are reported by LabVIEW, my application or the REFPROPdll prior to the crash.  The crash only occurs while the REFPROPdll is being called.

### Versions

**REFPROP Version:** 10
**Operating System and Version:** Windows 7
**Access Method:** Call Library Function Node in LabVIEW

**Comment by ianhbell** [comment] 2018-10-09 18:37
What inputs are you providing to the REFPROP function?

**Comment by P-Erickson** [comment] 2018-10-09 18:46
My application calls for a number of different outputs, so inputs will vary, but a total list would be:

Fluid: Water
Units: SI with C

Property Inputs:
Temperature & Pressure (Liquid) - TPL
Temperature & Pressure (Vapor) - TPV
Saturation Pressure - Psat
Saturation Temperature - Tsat
Pressure & Enthalpy - PH

Property Outputs:
Density - D
Temperature - T
Pressure - P
Enthalpy - H
Quality - Qmass

**Comment by ianhbell** [comment] 2018-10-09 21:08
The only way we have a prayer of replicating and fixing this behavior is if you can come up with a set of inputs that can guarantee the crash.  Can you replicate this behavior detached from your DAQ system?  If so, please let us know the sequence of calls to REFPROPdll function that result in the failure.  A log of all the inputs you have provided to the function would be fine. You can email me the log at ian.bell@nist.gov

**Comment by P-Erickson** [comment] 2018-10-09 21:18
I am capable of executing the code external from my DAQ system using simulated measurement values as inputs.  As my experience up until this point is that I require at least 8 hours of run time prior to a system failure, it will take me a while to generate the data sets but I will begin on this now and share the information once I have it available.  In an effort to simplify the process, unless you indicate that you would prefer otherwise, I will start with only a single set of inputs to the REFPROPdll call (e.g. "D","Water","TPL","SI with C") and then cycle through others if necessary.

**Comment by ianhbell** [comment] 2018-10-10 07:27
Yeah, the simpler you can make the failing example, the better the chance that we might be able to find the error in short order.  Once I know the flow path, I can run memory checks in valgrind and add them to the tests we run: https://github.com/usnistgov/REFPROP-tests

**Comment by ianhbell** [comment] 2018-11-26 23:46
Any progress here?

**Comment by P-Erickson** [comment] 2018-12-06 17:19
Apologies for the delay in my response.  Given the length of time it takes to generate an error the progress has been slow.  

I've managed to reduce the calls to the REFPROPdll function down to Density & Pressure functions and still generate the failure however I've also made a new observation in that the issue appears to be associated with how the REFPROPdll function is called in LabVIEW.  In a series of tests where the REFPROPdll is called dynamically in LabVIEW the failure appears consistently however if the REFPROPdll is called statically, at least in the few cases I've run using identical inputs and call sequence, the failure hasn't appeared.  I'm uncertain if this helps from a trouble shooting perspective, but it is something I've observed.

The minimum specific calls (and the sequence of calls) to the REFPROPdll where I've observed the failure at this point is as follows:

refprop("D","Water","TPL","SI with C",~Inputs~)
refprop("P","Water","Tsat","SI with C",~Inputs~)
refprop("D","Water","TPL","SI with C",~Inputs~)
refprop("P","Water","Tsat","SI with C",~Inputs~)
refprop("P","Water","Tsat","SI with C",~Inputs~)

Sequences that don't include at least 5 function calls do not appear to generate the fault.

I'm continuing to attempt to reduce this to simplify the troubleshooting as much as possible, but to date this is the best I've managed.

**Comment by ianhbell** [comment] 2018-12-06 17:53
Thanks for the additional information.  What do you mean by calling the REFPROPdll function dynamically versus calling it statically?

Also, what are the numerical values of the inputs in particular that cause this problem?

**Comment by P-Erickson** [comment] 2018-12-06 18:20
Within LabVIEW I have the option of calling a VI statically by placing the VI containing the code directly into the block diagram (source code) or dynamically by calling the VI containing the code through a reference which is created through a function fed the target path as an input.

For our main acquisition application, as the equations we will use vary between programs, we typically call these types of functions dynamically for flexibility.  Which is where I began with my testing.  However I also built additional code that allows me to call the REFPROPdll VI statically to test separately.  When I did this I made the observation that I've only been able to generate the failures when I call the REFPROPdll VI in dynamically referenced VIs.  At least up until this point.

For the numerical values, as I've decoupled the code from my DAQ hardware I am using simulated inputs that cycle the numerical values of the input channels as a rate of approximately 0.05 Hz (about 3 cycles per minute).  The ranges of values are as follows:

refprop("D","Water","TPL","SI with C",~Inputs~)  T Input Range: 10 to 260C, P Input Range: 0.006 to 10.515 MPa
refprop("P","Water","Tsat","SI with C",~Inputs~)  Tsat Input Range: 10 to 260C
refprop("D","Water","TPL","SI with C",~Inputs~)  T Input Range: 0 to 260C, P Input Range: 0.006 to 10.515 MPa
refprop("P","Water","Tsat","SI with C",~Inputs~)  Tsat Input Range: 0 to 260C
refprop("P","Water","Tsat","SI with C",~Inputs~)  Tsat Input Range: 0 to 260C

As the input ranges cycle between defined limits and aren't bound to an actual physical channel it is expected that out of range errors will occur, in those circustances the errors are ignored and the output values of the dll are forced to a specified value by additional external code.  However the failures were still observed when the REFPROP inputs were tied to physical measurements or forced to values that were within physically possible ranges that would not generate an error.

**Comment by ianhbell** [comment] 2018-12-10 01:39
Can you please provide a bit more information about the exact order of calls that you are making?  It might be important that we carry out the exact same calls as you.  As it stands, I can’t see how to precisely reproduce your test on my computer.  I also have access to Labview, so a VI would also be fine.

Do you have the ability to do the same test in some environment other than Labview? That would help us to identify whether the issue is in REFPROP itself or in the Labview wrapper somehow.

**Comment by damianlauria** [comment] 2018-12-10 17:10
That’s an interesting issue. I’ll have to think about it a bit, but off the top of my head, I’d say it’s possible that because you're dynamically calling the VIs, a memory leak could develop if you're not explicitly closing your references each and every time. LabVIEW doesn’t close references for you, so you have to be very careful when you use them.

    On the other hand, the behavior that you describe with LabVIEW crashing all the way out with no warning usually indicates an internal problem with a dll. LabVIEW crashes out like that as a last line of defense if it thinks the dll is corrupting your system.
    
    Can you post your code or some screenshots? We might be able to recreate the problem here and take a closer look.

**Comment by P-Erickson** [comment] 2018-12-12 23:13
Afternoon Gentlemen,

I'll make an effort to generate a piece of LabVIEW code that replicates the issues independent of any other code that I normally use and that I can distribute to you as soon as I'm able.  However I'll offer in advance that this make take me a while to work in with some of my other year end activities.  If you can confirm what version of LabVIEW you're using I'll make sure to provide the appropriate revision.

In regards to the order of calls, they are as I've specified in my post on December 6th.  To date, this is the 'simplest' sequence I've found in which I can execute the calls to the Refprop.dll and consistently observe the problem.  I'm happy to inquire with some of our other developers to see if they have time to attempt to replicate the issue that I'm seeing in a different environment however as they're outside of my group I'm not sure what priority they'll be able to give this initially.

As for the functionality of the dynamic calls to the VI, my code is setup such that I open a reference to the VI once on initialization and it is held open until the user either calls for a termination of the application or disables that set of calculated channels at which point it is closed.  I've had repeatable success using this approach previously so my initial thoughts are that, while possible, a memory failure due to the reference call is a low probability.

In regards to screen shots, the code for the main VI that calls the Refprop.dll looks as follows:

![image](https://user-images.githubusercontent.com/44000073/49903642-18e97c00-fe25-11e8-8726-331a6d70959e.png)

![image](https://user-images.githubusercontent.com/44000073/49903655-269f0180-fe25-11e8-8699-790f96c5cb8e.png)

In it, the first image shows the VI that dynamically calls the code found in the second image, which contains a series of calls to a number of different calculated channels including those containing the Refprop.dll.  For my troubleshooting I selectively disable the calculated channels one at a time as I attempt to find the simplest failure call sequence.  The implementation of the DLL specific code internal to those calculated channels is identical to that in the example code that you've provided, with some minor modifications to the structures (typedefs) used to pass the data into and out of the VI.

However, when I call the same Refprop functions in the following way:

![image](https://user-images.githubusercontent.com/44000073/49903783-85fd1180-fe25-11e8-9612-897c4ad0876b.png)

I have not observed the issue.  The primary difference between these two types of calls is that in the first I'm calling the VI dynamically, and in the second I'm calling them statically.  All of the other variables are for the most part consistent (call rate, input ranges, execution of my primary code in parallel).  Now while I'm not certain that the issue would not be observed in the second configuration, I did let it run for enough time that I'm comfortable saying that it's a low probability.  (Dynamic calls: Failure within 10 to 24 hours, Static Calls: Run time of 4 days without failure)

**Comment by P-Erickson** [comment] 2018-12-17 17:39
Morning Gentlemen,

As I work on developing a piece of LabVIEW code that I can post and which replicates the issue, I wanted to inquire to see if you're familiar with the use of NI's Measurement & Automation Explorer (MAX)?  

Typically we use this for our hardware configuration and in cases like these the creation of simulated channels.  However if you're unfamiliar with it I will work to create all the channels and scales within the LabVIEW environment and avoid use of the NI-DAQmx drivers.  

If you can let me know if one, or both, of you have familiarity with and access to MAX and/or the NI-DAQmx drivers I will create my code accordingly.

**Comment by ianhbell** [comment] 2018-12-17 22:16
Hopefully @damianlauria can test your code - he's got the full suite of NI tooling

**Comment by damianlauria** [comment] 2018-12-17 22:37
Yes, I am familiar with MAX and I have the DAQmx drivers installed.

**Comment by EricLemmon** [comment] 2019-04-03 14:31
Has this issue been resolved?

**Closed** 2019-04-03 15:02 UTC
Labels: labview
