### ISSUE TITLE
REFPROP LabVIEW Integration

### ISSUE THREAD

**Issue by samikusi20** [usnistgov/REFPROP-wrappers#97] opened 2019-02-28 19:11 UTC
I am trying to use the attached VI but the LabVIEW code is not able to able to recognize the function with refprop dll file linked.  Please see screen shots below. Tried different file paths but does not seem to resolve it. Please advise which file path to use in order to utilize these functions.

![refprop dll call library_1](https://user-images.githubusercontent.com/48102852/53591860-07318e00-3b63-11e9-8d8c-47605cc1d225.png)
![refprop dll call library_2](https://user-images.githubusercontent.com/48102852/53591861-07ca2480-3b63-11e9-96be-75c9d69043c7.png)

**Comment by ianhbell** [comment] 2019-02-28 19:17
I take it you are using REFPROP 9.1?  If so, the ``REFPROPdll`` function is not available, as it was one of the "killer" features we added in REFPROP 10.  So if you would like to use the ``REFPROPdll`` function, you'll need to upgrade to version 10, or the old legacy interface is still available through the other VI for the legacy interface.

**Comment by samikusi20** [comment] 2019-02-28 19:38
thanks Ian. I am currently using REFPROP 9.1. Can you please advise which other VIs will support REFPROP 9.1? Link below is where I was searching for the VIs.
https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/Labview/REFPROP/VIs

**Comment by ianhbell** [comment] 2019-02-28 19:44
The functions here are, with few exceptions, exposed in the REFPROP 9.x interface: https://github.com/usnistgov/REFPROP-wrappers/issues/97#issuecomment-468408492 .  But it's more involved because you need to call SETUPdll prior to doing any calculations.

**Comment by ianhbell** [comment] 2019-02-28 19:48
The Labview interface we provide is _really_ focused on REFPROP 10, but it does work with 9.x

**Comment by samikusi20** [comment] 2019-02-28 20:45
ok does that mean I will need to have two VIs (Call Library Functions); one for Setupdll and the other for SATPdll? how does one feed into the other?

**Comment by ianhbell** [comment] 2019-02-28 20:56
They don't exactly feed into each other.  First you call SETUPdll (make sure to check the ierr for errors), then you call SATPdll.

**Comment by samikusi20** [comment] 2019-02-28 21:27
got it thanks. Will try that and see how it goes. realized that both functions I referenced earlier does not have input to select type of refrigerant. I'm looking to calculate saturated pressure and temperature values? What will be the best function you would recommend for this?

**Comment by ianhbell** [comment] 2019-02-28 22:15
STEUPdll does: https://refprop-docs.readthedocs.io/en/latest/DLL/legacy.html#f/_/SETUPdll

**Comment by samikusi20** [comment] 2019-03-01 17:18
Can you please advise what I am doing wrong in the screen shots below. Error in opening up fluid files.
Is it the name of the file or file path reference?

![setupdll call library](https://user-images.githubusercontent.com/48102852/53654600-1d4f5500-3c1c-11e9-9f63-46371181b8af.PNG)
![setupdll front panel](https://user-images.githubusercontent.com/48102852/53654601-1d4f5500-3c1c-11e9-8999-f91b1d2b1cb2.PNG)

**Comment by ianhbell** [comment] 2019-03-01 17:23
Did you copy the FLUIDS and MIXTURES directories to your Labview REFPROP wrapper?

**Comment by ianhbell** [comment] 2019-03-01 17:29
You shouldn't need to do this, but it is possible that you might need to provide absolute paths to the fluid file, because I am not sure where the current working directory is for Labview, and although REFPROP looks for FLUID files relative to the current working directory, in many programs the CWD is not what you think it is.

**Comment by samikusi20** [comment] 2019-03-01 20:32
Please see below for the file structure and advise.

![setupdll project explorer](https://user-images.githubusercontent.com/48102852/53664697-46311380-3c37-11e9-9e53-f45febd5212a.PNG)

**Comment by samikusi20** [comment] 2019-03-01 20:34
Also can you please advise if the reprop dll files are generated in C/C++ or .NET?

**Comment by ianhbell** [comment] 2019-03-01 20:41
What happened to the FLUIDS and MIXTURES folders?  You should have populated them with the .FLD files from REFPROP installation.  I'll update the docs to make more clear, but there is a comment in the README: "You will also need to copy the FLUIDS and MIXTURES files form your copy of REFPROP into the empty folders in the wrapper’s directory."

**Comment by samikusi20** [comment] 2019-03-04 22:02
Hi Ian,

Fluids and mixture folders have been added still getting the same error when running SETUPdll. Please my entire project folder and image of the project explorer as well. 
![refprop dll project explorer](https://user-images.githubusercontent.com/48102852/53765841-200dac80-3e9f-11e9-824d-733dc105e4e8.PNG)
[REPROP LABVIEW.zip](https://github.com/usnistgov/REFPROP-wrappers/files/2928371/REPROP.LABVIEW.zip)

Please advise.

**Comment by ianhbell** [comment] 2019-03-04 22:21
I had to modify your last post to delete the REFPROP files, which are protected IP.

**Comment by ianhbell** [comment] 2019-03-04 22:27
@usnistgov/oism-labautomation Can you help this user out?

**Comment by ianhbell** [comment] 2019-03-04 22:29
@usnistgov/oism-labautomation Sorry that was intended for Damian

**Comment by samikusi20** [comment] 2019-03-05 15:07
Hi Damian, can you please advise on the code sent?
We are in a little bit of a crunch time so any help will be greatly appreciated.

**Comment by ianhbell** [comment] 2019-03-05 16:26
If you are really pushed time-wise, you might want to try the CoolProp wrapper for Labview: http://www.coolprop.org/coolprop/wrappers/Labview/index.html#labview .  For simple use cases, its easier to get going than the full-on REFPROP wrapper.  You would then just pass the fluid name as something like "REFPROP::WATER" for water.

**Comment by damianlauria** [comment] 2019-03-05 23:12
How did you set up your folder structure for the wrapper? By default, the wrapper VIs are set to look in the REFPROP folder for the dll and the FLUIDS and MIXTURES folders (which you'll have to add yourself) for those files. None of those files are in the wrapper because they're sold with REFPROP, so you'll have to add them yourself. 
      The readme file has a picture of the folder structure if that helps. It shouldn't be necessary to add any of those files to your LabVIEW project. They'll get pulled in automatically. 
      Also, the example program provided in the REFPROP folder uses only older functionality that was provided in the 9.x versions of REFPROP, so it should show you how to do most of what you need. Please let me know if you need more assistance.

**Comment by samikusi20** [comment] 2019-03-08 17:12
Hi Damian/Ian, I downloaded the Refprop example vi along with the support VIs and Utility files. 
This file does not work for all refrigerants. It was missing R404A so I added to the list but program not able execute. How do get this to work with R404A?

**Comment by samikusi20** [comment] 2019-03-08 17:18
Error 501 (MEL TK error 501) Equation not available

**Comment by ianhbell** [comment] 2019-03-08 19:51
R404A is available as a pseudo-pure fluid and a predefined mixture; which one did you use?

FYI: Melting lines are not available for all fluids/mixtures, though they are available for some.

**Comment by samikusi20** [comment] 2019-03-08 20:34
I ran this as mixture. Entered Fluid as R404A.MIX
Tried running again and this time no error but its not providing the correct saturation values.
![R404A_LabVIEW Refprop Example](https://user-images.githubusercontent.com/48102852/54054205-93713000-41b7-11e9-8bf1-899016df7870.PNG)
![R404A_Utility Calculate](https://user-images.githubusercontent.com/48102852/54054206-93713000-41b7-11e9-9e62-ab8d6a5a128f.PNG)

**Comment by ianhbell** [comment] 2019-03-08 20:40
Units? REFPROP 9.1 always uses K as temperature.  See the MANUAL.TXT file in the FORTRAN folder of your installation

**Comment by samikusi20** [comment] 2019-03-08 21:20
that doesn't even seem right either. Even for other refrigerants, calculations are off as well

![image](https://user-images.githubusercontent.com/48102852/54056372-dcc47e00-41bd-11e9-9a6f-2ebb9dbb69b4.png)

![image](https://user-images.githubusercontent.com/48102852/54056430-0d0c1c80-41be-11e9-9d25-34bbff0e67ea.png)

**Comment by ianhbell** [comment] 2019-03-08 21:32
What did you specify as your second input? You always need two independent variables to specify the phase.

**Comment by samikusi20** [comment] 2019-03-08 22:21
I am specifying only one input. I am basically trying to use the equivalent of the excel function Pressure() to calculate saturation pressure given a temperature input

**Comment by ianhbell** [comment] 2019-03-08 22:23
Then you also need to specify the value of vapor quality “Q” to be zero or one for saturated liquid or vapor, respectively.

**Comment by samikusi20** [comment] 2019-03-08 23:16
where would i specify this value? this is not an input on the front panel

**Comment by ianhbell** [comment] 2019-03-08 23:18
I think the empty box on the front panel should be selected to be “Q”.

**Comment by samikusi20** [comment] 2019-03-08 23:23
that's an output from the code when you have a second input

**Comment by ianhbell** [comment] 2019-03-08 23:25
This one: ?

![image](https://user-images.githubusercontent.com/11966765/54061590-c79c1f00-41be-11e9-9db6-9db127f1e803.png)

**Comment by samikusi20** [comment] 2019-03-08 23:35
yes thats correct. and I think this code is expected temperature units to be in C. when I enter 293, error states temp is out of range. because its reading as 293C.

![image](https://user-images.githubusercontent.com/48102852/54061900-ffac5d80-41d0-11e9-9232-74f3b16f8052.png)

**Comment by damianlauria** [comment] 2019-03-08 23:48
Looking under the hood, it does look like it's expecting temperature in C. It's just adding 273.15 to anything that you put in that box. Use that and input code TQ and I think you'll have more success.

**Comment by EricLemmon** [comment] 2019-03-28 03:56
If this issue has been resolved, would you close it?

**Closed** 2019-03-29 20:49 UTC
Labels: labview
