### ISSUE TITLE
Python Wrapper needs better path handling and documentation.

### ISSUE THREAD

**Issue by techdragon** [usnistgov/REFPROP-wrappers#42] opened 2018-06-10 13:03 UTC
- The error 101 output doesn't make clear just 'where' it failed to find a particular file, making it very hard to determine the cause of "unable to find" type errors. `[SETUP error 101] Error in opening file for component 1: filename = Water.FLD` isn't terribly helpful. Perhaps a path debugging flag or environment variable to change this to a more verbose behaviour? It would be extremely helpful to know _where_ it was trying to find the file to open it.
- The examples/tutorials don't make it clear that `REFPROPdll()` can take the full/absolute path to the fluid file and avoid any path related issues. It is in the documentation, but its worth also mentioning it in the examples as they are trying to guide users through some basic usage of the wrapper. 
- I was unable to get the python wrapper to work on macOS without passing it absolute paths to fluid/mixture files. It seems like every combination of `RPPREFIX` was useless and I had to give up and tried absolute paths by chance. (See previous point) 
- It really shouldn't be too hard to make the python wrapper handle the filename case sensitivity stuff better. (I'll try and find time to implement this myself and I'll open a PR for it. 😄 )

**Comment by ianhbell** [comment] 2018-06-11 15:29
First off, thanks for the report.  Some good ideas in here.

1. This is with 9.1.1, right?  10.0 gives a more useful error message, but yes, file loading is still a thing.  This is one of the core problems with REFPROP, and why we should compile the fluid files into the DLL.
2. Good point, I'll make that change.
3. Did you call ``SETPATHdll``?  I'm going to guess not, or maybe, you set it incorrectly, because if you have that set up properly on OSX, it all just works.  You should have a folder (to which ``RPPREFIX`` gets pointed) with the ``librefprop.dylib``, and ``FLUIDS`` and ``MIXTURES``.  Then RPPREFIX gets pointed to the folder tha 
4. It's actually not as trivial as you think, I think.  There are a lot of corner cases that are special (loading ECS fluids, predefined mixtures, etc.) that need to be done in a special way.

**Comment by techdragon** [comment] 2018-06-12 14:20
1.  I think its the latest 10.0. The  RefProp download is definitely 10.0 in my Windows VM, and I've built the the CMake bindings repo from source with the latest gcc & gfortran from Homebrew on my Mac. The python bindings are `ctREFPROP==0.6.1`. So I'm not exactly sure how to call it _properly_ 10.0 or not. If mismatch has occurred during the CMake build, I'm not sure where. I followed the compile instructions and the only issues were a few minor capitalisation issues, and a file that was in a subfolder when it should have been 1 level higher in the directory tree for it to find it during the build. Otherwise everything built/installed without issues.

2. Thanks 👍 

3. 1. Thats the ticket. ✅ You guessed 100% correctly!  🎉 
    2. I've found the documentation, and the place where its used in the python examples ... _but_ its only used once, and thats in the section for the legacy 9.1 example (This does make me more curious if something is weird with the CMake built bindings or the python library 🤔). Assuming that nothing is wrong with my install, and `SETPATHdll` is still needed when running on Mac and/or Linux for version 10.0, then it would probably be worth mentioning, at least in the comments of the 10.0 section on https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python, and definitely needs to be mentioned in the Jupyter notebook tutorial/examples here https://github.com/usnistgov/REFPROP-wrappers/tree/master/wrappers/python/notebooks

4. I'm sure you know it better than I do, I have no doubt it may be non trivial work to change it in the DLL and/or Bindings, but it still seems like making the Python wrapper a little smarter, should be a _weekend sized_ piece of work. Of course this is said with my optimist hat firmly on my head and without adequate inspection of the code. But I'm glad to hear its something you are aware of and that there are understandable reasons why the loading is the way it currently is. It is genuinely refreshing to hear "there are special cases to account for" when, as a programmer I've become so used to hearing the answer as "we haven't got around to that yet because it doesn't matter and/or we never thought about it" :soil

**Comment by ianhbell** [comment] 2018-06-12 19:44
1. Can you please file issues at REFPROP-cmake with every single thing that you had to modify or update to get it to build seamlessly?  I want to make it an enjoyable and clean experience for everyone (I think I know what the problem is, but I just want to be sure I don't assume).  
2. Changed: https://github.com/usnistgov/REFPROP-wrappers/commit/77567da659f597830843de34e29b5e6b6129fc05
3. Also added: https://github.com/usnistgov/REFPROP-wrappers/commit/77567da659f597830843de34e29b5e6b6129fc05 .  To be honest, I'm not sure how the code in my notebook EVER worked without the call to ``SETPATHdll`` (oversight on my part), but there must have been some magic happening behind the scenes.  Also, updated the README: https://github.com/usnistgov/REFPROP-wrappers/commit/597c522e22e7ecdedb3ccdc65014bf95aeac7e21
4. The short answer is: ALWAYS USE UPPER CASE FLUID NAMES.  That will work on windows, which doesn't care about case, and all fluid files have uppercase names, so uppercase names will work on more case sensitive platforms too.  The magical aliases ("Water" for instance) map to uppercase names.  But to be sure, always use upper case.  That is the standard applied consistently throughout REFPROP, and tests (https://github.com/usnistgov/REFPROP-tests) suggest that it works properly.  If that *doesn't* work, it's a bug and the filing of an issue would be appreciated.

Gold-star bug report of the week!

**Comment by EricLemmon** [comment] 2019-03-29 19:42
If all issues with this have been resolved, could you close this issues?

**Closed** 2019-03-29 21:19 UTC
Labels: python
